# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_price', models.IntegerField(default=0)),
                ('items', models.IntegerField(default=0)),
                ('units', models.CharField(choices=[('KG', 'KiloGrams'), ('G', 'Grams'), ('Units', 'units')], max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Product')),
            ],
        ),
    ]
