# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='product_id',
        ),
    ]
