# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20161227_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='product_id',
            new_name='product',
        ),
    ]
