# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20161227_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Purchase_price',
            field=models.IntegerField(default=0),
        ),
    ]
