# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_purchase_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Company'),
            preserve_default=False,
        ),
    ]
