# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20161227_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Inventory.Company'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Inventory.Product'),
        ),
    ]
