# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_auto_20161227_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.ForeignKey(db_column='code', default='001', on_delete=django.db.models.deletion.CASCADE, to='Inventory.Product'),
            preserve_default=False,
        ),
    ]
