# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_purchase_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='code',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Company'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(to='Inventory.Product'),
        ),
    ]
