# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20161228_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.ForeignKey(db_column='code', default='001', on_delete=django.db.models.deletion.CASCADE, to='Inventory.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Inventory.Company'),
        ),
    ]
