# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_auto_20161228_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='code',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Inventory.Product'),
        ),
    ]
