# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_purchase_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='name',
        ),
    ]
