# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_auto_20161228_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
    ]
