# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
