# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_auto_20170101_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(default='Kg', max_length=25),
            preserve_default=False,
        ),
    ]
