# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
