# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_stock_pur_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField(max_length=8)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UN', 'Unpaid'), ('P', 'Paid')], max_length=5)),
                ('cust_name', models.CharField(max_length=250)),
                ('cust_add', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=10)),
                ('invoice_id', models.ForeignKey(db_column='invoice_num', on_delete=django.db.models.deletion.CASCADE, to='Inventory.InvoiceDetail')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Product')),
            ],
        ),
    ]
