# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_invoicedetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Purchase'),
            preserve_default=False,
        ),
    ]
