# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_auto_20170105_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice_num',
            field=models.IntegerField(unique=True),
        ),
    ]
