# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0027_auto_20170106_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
